# Generated by Django 4.2 on 2024-06-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategorymodel',
            name='tasks',
        ),
    ]
