# Generated by Django 4.2 on 2024-06-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(max_length=400)),
                ('is_completed', models.BooleanField(default=False)),
                ('assign_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
