# Generated by Django 4.2 on 2024-06-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0002_remove_taskcategorymodel_tasks'),
        ('task_model', '0003_alter_taskmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_category',
            field=models.ManyToManyField(to='task_category.taskcategorymodel'),
        ),
    ]
